service: greeter-crud

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  hello:
    handler: src/main.hello
    events:
      - http:
          path: /v1/greetings
          method: get

plugins:
  - serverless-plugin-typescript